INSERT INTO USUARIO(NOME, EMAIL, SENHA) VALUES('ALUNO', 'ALUNO@EMAIL.COM', '123456');

INSERT INTO CURSO(NOME, CATEGORIA) VALUES('SPRING BOOT', 'PROGRAMACAO');
INSERT INTO CURSO(NOME, CATEGORIA) VALUES('HTML 5', 'FRONT-END');

INSERT INTO TOPICO(TITULO, MENSAGEM, DATA_CRIACAO, STATUS, AUTOR_ID, CURSO_ID) VALUES('DUVIDA', 'ERRO AO CRIAR PROJETO', '2019-05-05 18:00:00', 'NAO_RESPONDIDO', 1, 1);
INSERT INTO TOPICO(TITULO, MENSAGEM, DATA_CRIACAO, STATUS, AUTOR_ID, CURSO_ID) VALUES('DUVIDA 2', 'PROJETO NAO COMPILA', '2019-05-05 19:00:00', 'NAO_RESPONDIDO', 1, 1);
INSERT INTO TOPICO(TITULO, MENSAGEM, DATA_CRIACAO, STATUS, AUTOR_ID, CURSO_ID) VALUES('DUVIDA 3', 'TAG HTML', '2019-05-05 20:00:00', 'NAO_RESPONDIDO', 1, 2);

